name: Deploy to GCP Cloud Storage

on:
  push:
    branches:
      - main  # メインブランチへのプッシュ時に実行

env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_BUCKET_NAME: ${{ secrets.GCP_BUCKET_NAME }}
  GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build
        env:
          GATSBY_ACTIVE_ENV: production

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ env.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Deploy to Cloud Storage
        run: |
          gsutil -m rsync -d -r public/ gs://${{ env.GCP_BUCKET_NAME }}/
          gsutil iam ch allUsers:objectViewer gs://${{ env.GCP_BUCKET_NAME }} 